### ISSUE TITLE
ToDo paper

### ISSUE THREAD

**Issue by Yagami360** [Yagami360/MachineLearning-Papers_Survey#20]
- Neural Networks
    - [ ]  ODENet [Neural Ordinary Differential Equations]
    - [ ] Kervolutional Neural Networks

- GANs
    - [ ] WGAN-gp
    - [ ] Boundless: Generative Adversarial Networks for Image Extension
